### ISSUE TITLE
How do presets work?

### ISSUE THREAD

**Issue by kittylegitcheck** [SmartGiveaways/smart-giveaway-bot#43]
How do presets work?

**Comment by ZakShearman** [comment]
A giveaway has a preset assigned to it. A preset is a bunch of settings that will be used for running a giveaway.

Anything in particular you want to know about them?

**Comment by kittylegitcheck** [comment]
What kind of settings? If i can save my custom ones, than how do i do that? And if i do that how do i launch a giveaway from preset?

**Comment by ZakShearman** [comment]
Please use the help commands of the bot which show this

**Comment by kittylegitcheck** [comment]
Okay thanks!
